<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/passulo/token.proto

namespace Com\Passulo\V1\Token;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.passulo.v1.Token.Gender</code>
 */
class Gender
{
    /**
     * Generated from protobuf enum <code>undefined = 0;</code>
     */
    const undefined = 0;
    /**
     * Generated from protobuf enum <code>female = 1;</code>
     */
    const female = 1;
    /**
     * Generated from protobuf enum <code>male = 2;</code>
     */
    const male = 2;
    /**
     * Generated from protobuf enum <code>diverse = 3;</code>
     */
    const diverse = 3;

    private static $valueToName = [
        self::undefined => 'undefined',
        self::female => 'female',
        self::male => 'male',
        self::diverse => 'diverse',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Gender::class, \Com\Passulo\V1\Token_Gender::class);

