// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: com/passulo/token.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Passulo.V1 {

  /// <summary>Holder for reflection information generated from com/passulo/token.proto</summary>
  public static partial class TokenReflection {

    #region Descriptor
    /// <summary>File descriptor for com/passulo/token.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TokenReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chdjb20vcGFzc3Vsby90b2tlbi5wcm90bxIOY29tLnBhc3N1bG8udjEaH2dv",
            "b2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8i/wIKBVRva2VuEgoKAmlk",
            "GAEgASgJEhEKCWZpcnN0TmFtZRgCIAEoCRISCgptaWRkbGVOYW1lGAMgASgJ",
            "EhAKCGxhc3ROYW1lGAQgASgJEiwKBmdlbmRlchgFIAEoDjIcLmNvbS5wYXNz",
            "dWxvLnYxLlRva2VuLkdlbmRlchIOCgZudW1iZXIYBiABKAkSDgoGc3RhdHVz",
            "GAcgASgJEg8KB2NvbXBhbnkYCCABKAkSDQoFZW1haWwYCSABKAkSEQoJdGVs",
            "ZXBob25lGAogASgJEhMKC2Fzc29jaWF0aW9uGAsgASgJEi4KCnZhbGlkVW50",
            "aWwYDCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi8KC21lbWJl",
            "clNpbmNlGA0gASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI6CgZH",
            "ZW5kZXISDQoJdW5kZWZpbmVkEAASCgoGZmVtYWxlEAESCAoEbWFsZRACEgsK",
            "B2RpdmVyc2UQA0InCgtjb20ucGFzc3Vsb1oYZ2l0aHViLmNvbS9wYXNzdWxv",
            "L1Rva2VuYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Passulo.V1.Token), global::Com.Passulo.V1.Token.Parser, new[]{ "Id", "FirstName", "MiddleName", "LastName", "Gender", "Number", "Status", "Company", "Email", "Telephone", "Association", "ValidUntil", "MemberSince" }, null, new[]{ typeof(global::Com.Passulo.V1.Token.Types.Gender) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Token : pb::IMessage<Token>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Token> _parser = new pb::MessageParser<Token>(() => new Token());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Token> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Passulo.V1.TokenReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token(Token other) : this() {
      id_ = other.id_;
      firstName_ = other.firstName_;
      middleName_ = other.middleName_;
      lastName_ = other.lastName_;
      gender_ = other.gender_;
      number_ = other.number_;
      status_ = other.status_;
      company_ = other.company_;
      email_ = other.email_;
      telephone_ = other.telephone_;
      association_ = other.association_;
      validUntil_ = other.validUntil_ != null ? other.validUntil_.Clone() : null;
      memberSince_ = other.memberSince_ != null ? other.memberSince_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Token Clone() {
      return new Token(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    /// <summary>
    /// identifier for this token only
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firstName" field.</summary>
    public const int FirstNameFieldNumber = 2;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middleName" field.</summary>
    public const int MiddleNameFieldNumber = 3;
    private string middleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MiddleName {
      get { return middleName_; }
      set {
        middleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lastName" field.</summary>
    public const int LastNameFieldNumber = 4;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 5;
    private global::Com.Passulo.V1.Token.Types.Gender gender_ = global::Com.Passulo.V1.Token.Types.Gender.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Com.Passulo.V1.Token.Types.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 6;
    private string number_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Number {
      get { return number_; }
      set {
        number_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 7;
    private string status_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "company" field.</summary>
    public const int CompanyFieldNumber = 8;
    private string company_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Company {
      get { return company_; }
      set {
        company_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 9;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telephone" field.</summary>
    public const int TelephoneFieldNumber = 10;
    private string telephone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Telephone {
      get { return telephone_; }
      set {
        telephone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "association" field.</summary>
    public const int AssociationFieldNumber = 11;
    private string association_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Association {
      get { return association_; }
      set {
        association_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "validUntil" field.</summary>
    public const int ValidUntilFieldNumber = 12;
    private global::Google.Protobuf.WellKnownTypes.Timestamp validUntil_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ValidUntil {
      get { return validUntil_; }
      set {
        validUntil_ = value;
      }
    }

    /// <summary>Field number for the "memberSince" field.</summary>
    public const int MemberSinceFieldNumber = 13;
    private global::Google.Protobuf.WellKnownTypes.Timestamp memberSince_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp MemberSince {
      get { return memberSince_; }
      set {
        memberSince_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Token);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Token other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (FirstName != other.FirstName) return false;
      if (MiddleName != other.MiddleName) return false;
      if (LastName != other.LastName) return false;
      if (Gender != other.Gender) return false;
      if (Number != other.Number) return false;
      if (Status != other.Status) return false;
      if (Company != other.Company) return false;
      if (Email != other.Email) return false;
      if (Telephone != other.Telephone) return false;
      if (Association != other.Association) return false;
      if (!object.Equals(ValidUntil, other.ValidUntil)) return false;
      if (!object.Equals(MemberSince, other.MemberSince)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (MiddleName.Length != 0) hash ^= MiddleName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Gender != global::Com.Passulo.V1.Token.Types.Gender.Undefined) hash ^= Gender.GetHashCode();
      if (Number.Length != 0) hash ^= Number.GetHashCode();
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      if (Company.Length != 0) hash ^= Company.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Telephone.Length != 0) hash ^= Telephone.GetHashCode();
      if (Association.Length != 0) hash ^= Association.GetHashCode();
      if (validUntil_ != null) hash ^= ValidUntil.GetHashCode();
      if (memberSince_ != null) hash ^= MemberSince.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastName);
      }
      if (Gender != global::Com.Passulo.V1.Token.Types.Gender.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      if (Number.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Number);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Status);
      }
      if (Company.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Company);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Email);
      }
      if (Telephone.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Telephone);
      }
      if (Association.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Association);
      }
      if (validUntil_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(ValidUntil);
      }
      if (memberSince_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(MemberSince);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (FirstName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(LastName);
      }
      if (Gender != global::Com.Passulo.V1.Token.Types.Gender.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gender);
      }
      if (Number.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Number);
      }
      if (Status.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Status);
      }
      if (Company.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Company);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Email);
      }
      if (Telephone.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(Telephone);
      }
      if (Association.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(Association);
      }
      if (validUntil_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(ValidUntil);
      }
      if (memberSince_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(MemberSince);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (MiddleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MiddleName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Gender != global::Com.Passulo.V1.Token.Types.Gender.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (Number.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Number);
      }
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      if (Company.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Company);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Telephone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Telephone);
      }
      if (Association.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Association);
      }
      if (validUntil_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ValidUntil);
      }
      if (memberSince_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MemberSince);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Token other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.MiddleName.Length != 0) {
        MiddleName = other.MiddleName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Gender != global::Com.Passulo.V1.Token.Types.Gender.Undefined) {
        Gender = other.Gender;
      }
      if (other.Number.Length != 0) {
        Number = other.Number;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
      if (other.Company.Length != 0) {
        Company = other.Company;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Telephone.Length != 0) {
        Telephone = other.Telephone;
      }
      if (other.Association.Length != 0) {
        Association = other.Association;
      }
      if (other.validUntil_ != null) {
        if (validUntil_ == null) {
          ValidUntil = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ValidUntil.MergeFrom(other.ValidUntil);
      }
      if (other.memberSince_ != null) {
        if (memberSince_ == null) {
          MemberSince = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        MemberSince.MergeFrom(other.MemberSince);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            MiddleName = input.ReadString();
            break;
          }
          case 34: {
            LastName = input.ReadString();
            break;
          }
          case 40: {
            Gender = (global::Com.Passulo.V1.Token.Types.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            Number = input.ReadString();
            break;
          }
          case 58: {
            Status = input.ReadString();
            break;
          }
          case 66: {
            Company = input.ReadString();
            break;
          }
          case 74: {
            Email = input.ReadString();
            break;
          }
          case 82: {
            Telephone = input.ReadString();
            break;
          }
          case 90: {
            Association = input.ReadString();
            break;
          }
          case 98: {
            if (validUntil_ == null) {
              ValidUntil = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ValidUntil);
            break;
          }
          case 106: {
            if (memberSince_ == null) {
              MemberSince = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MemberSince);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            FirstName = input.ReadString();
            break;
          }
          case 26: {
            MiddleName = input.ReadString();
            break;
          }
          case 34: {
            LastName = input.ReadString();
            break;
          }
          case 40: {
            Gender = (global::Com.Passulo.V1.Token.Types.Gender) input.ReadEnum();
            break;
          }
          case 50: {
            Number = input.ReadString();
            break;
          }
          case 58: {
            Status = input.ReadString();
            break;
          }
          case 66: {
            Company = input.ReadString();
            break;
          }
          case 74: {
            Email = input.ReadString();
            break;
          }
          case 82: {
            Telephone = input.ReadString();
            break;
          }
          case 90: {
            Association = input.ReadString();
            break;
          }
          case 98: {
            if (validUntil_ == null) {
              ValidUntil = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ValidUntil);
            break;
          }
          case 106: {
            if (memberSince_ == null) {
              MemberSince = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MemberSince);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Token message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Gender {
        [pbr::OriginalName("undefined")] Undefined = 0,
        [pbr::OriginalName("female")] Female = 1,
        [pbr::OriginalName("male")] Male = 2,
        [pbr::OriginalName("diverse")] Diverse = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
