// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/passulo/token.proto

package com.passulo;

public final class TokenOuterClass {
  private TokenOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.passulo.v1.Token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * identifier for this token only
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <pre>
     * identifier for this token only
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string middleName = 3;</code>
     * @return The middleName.
     */
    java.lang.String getMiddleName();
    /**
     * <code>string middleName = 3;</code>
     * @return The bytes for middleName.
     */
    com.google.protobuf.ByteString
        getMiddleNameBytes();

    /**
     * <code>string lastName = 4;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 4;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    int getGenderValue();
    /**
     * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
     * @return The gender.
     */
    com.passulo.TokenOuterClass.Token.Gender getGender();

    /**
     * <code>string number = 6;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 6;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string company = 8;</code>
     * @return The company.
     */
    java.lang.String getCompany();
    /**
     * <code>string company = 8;</code>
     * @return The bytes for company.
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>string email = 9;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 9;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string telephone = 10;</code>
     * @return The telephone.
     */
    java.lang.String getTelephone();
    /**
     * <code>string telephone = 10;</code>
     * @return The bytes for telephone.
     */
    com.google.protobuf.ByteString
        getTelephoneBytes();

    /**
     * <code>string association = 11;</code>
     * @return The association.
     */
    java.lang.String getAssociation();
    /**
     * <code>string association = 11;</code>
     * @return The bytes for association.
     */
    com.google.protobuf.ByteString
        getAssociationBytes();

    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return Whether the validUntil field is set.
     */
    boolean hasValidUntil();
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return The validUntil.
     */
    com.google.protobuf.Timestamp getValidUntil();
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     */
    com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return Whether the memberSince field is set.
     */
    boolean hasMemberSince();
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return The memberSince.
     */
    com.google.protobuf.Timestamp getMemberSince();
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     */
    com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder();
  }
  /**
   * Protobuf type {@code com.passulo.v1.Token}
   */
  public static final class Token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.passulo.v1.Token)
      TokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Token.newBuilder() to construct.
    private Token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Token() {
      id_ = "";
      firstName_ = "";
      middleName_ = "";
      lastName_ = "";
      gender_ = 0;
      number_ = "";
      status_ = "";
      company_ = "";
      email_ = "";
      telephone_ = "";
      association_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Token();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passulo.TokenOuterClass.Token.class, com.passulo.TokenOuterClass.Token.Builder.class);
    }

    /**
     * Protobuf enum {@code com.passulo.v1.Token.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>undefined = 0;</code>
       */
      undefined(0),
      /**
       * <code>female = 1;</code>
       */
      female(1),
      /**
       * <code>male = 2;</code>
       */
      male(2),
      /**
       * <code>diverse = 3;</code>
       */
      diverse(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>undefined = 0;</code>
       */
      public static final int undefined_VALUE = 0;
      /**
       * <code>female = 1;</code>
       */
      public static final int female_VALUE = 1;
      /**
       * <code>male = 2;</code>
       */
      public static final int male_VALUE = 2;
      /**
       * <code>diverse = 3;</code>
       */
      public static final int diverse_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Gender valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Gender forNumber(int value) {
        switch (value) {
          case 0: return undefined;
          case 1: return female;
          case 2: return male;
          case 3: return diverse;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.passulo.TokenOuterClass.Token.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gender(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.passulo.v1.Token.Gender)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <pre>
     * identifier for this token only
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * identifier for this token only
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firstName_ = "";
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIDDLENAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object middleName_ = "";
    /**
     * <code>string middleName = 3;</code>
     * @return The middleName.
     */
    @java.lang.Override
    public java.lang.String getMiddleName() {
      java.lang.Object ref = middleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        middleName_ = s;
        return s;
      }
    }
    /**
     * <code>string middleName = 3;</code>
     * @return The bytes for middleName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMiddleNameBytes() {
      java.lang.Object ref = middleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        middleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastName_ = "";
    /**
     * <code>string lastName = 4;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 4;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private int gender_ = 0;
    /**
     * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @java.lang.Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
     * @return The gender.
     */
    @java.lang.Override public com.passulo.TokenOuterClass.Token.Gender getGender() {
      com.passulo.TokenOuterClass.Token.Gender result = com.passulo.TokenOuterClass.Token.Gender.forNumber(gender_);
      return result == null ? com.passulo.TokenOuterClass.Token.Gender.UNRECOGNIZED : result;
    }

    public static final int NUMBER_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>string number = 6;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 6;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object status_ = "";
    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object company_ = "";
    /**
     * <code>string company = 8;</code>
     * @return The company.
     */
    @java.lang.Override
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 8;</code>
     * @return The bytes for company.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 9;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 9;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEPHONE_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile java.lang.Object telephone_ = "";
    /**
     * <code>string telephone = 10;</code>
     * @return The telephone.
     */
    @java.lang.Override
    public java.lang.String getTelephone() {
      java.lang.Object ref = telephone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telephone_ = s;
        return s;
      }
    }
    /**
     * <code>string telephone = 10;</code>
     * @return The bytes for telephone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTelephoneBytes() {
      java.lang.Object ref = telephone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telephone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSOCIATION_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile java.lang.Object association_ = "";
    /**
     * <code>string association = 11;</code>
     * @return The association.
     */
    @java.lang.Override
    public java.lang.String getAssociation() {
      java.lang.Object ref = association_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        association_ = s;
        return s;
      }
    }
    /**
     * <code>string association = 11;</code>
     * @return The bytes for association.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssociationBytes() {
      java.lang.Object ref = association_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        association_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDUNTIL_FIELD_NUMBER = 12;
    private com.google.protobuf.Timestamp validUntil_;
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return Whether the validUntil field is set.
     */
    @java.lang.Override
    public boolean hasValidUntil() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return The validUntil.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getValidUntil() {
      return validUntil_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
    }
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder() {
      return validUntil_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
    }

    public static final int MEMBERSINCE_FIELD_NUMBER = 13;
    private com.google.protobuf.Timestamp memberSince_;
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return Whether the memberSince field is set.
     */
    @java.lang.Override
    public boolean hasMemberSince() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return The memberSince.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getMemberSince() {
      return memberSince_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
    }
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder() {
      return memberSince_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, middleName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
      }
      if (gender_ != com.passulo.TokenOuterClass.Token.Gender.undefined.getNumber()) {
        output.writeEnum(5, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, company_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telephone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, telephone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(association_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, association_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(12, getValidUntil());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(13, getMemberSince());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, middleName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
      }
      if (gender_ != com.passulo.TokenOuterClass.Token.Gender.undefined.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, company_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telephone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, telephone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(association_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, association_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getValidUntil());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getMemberSince());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passulo.TokenOuterClass.Token)) {
        return super.equals(obj);
      }
      com.passulo.TokenOuterClass.Token other = (com.passulo.TokenOuterClass.Token) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getMiddleName()
          .equals(other.getMiddleName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (gender_ != other.gender_) return false;
      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getCompany()
          .equals(other.getCompany())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getTelephone()
          .equals(other.getTelephone())) return false;
      if (!getAssociation()
          .equals(other.getAssociation())) return false;
      if (hasValidUntil() != other.hasValidUntil()) return false;
      if (hasValidUntil()) {
        if (!getValidUntil()
            .equals(other.getValidUntil())) return false;
      }
      if (hasMemberSince() != other.hasMemberSince()) return false;
      if (hasMemberSince()) {
        if (!getMemberSince()
            .equals(other.getMemberSince())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + MIDDLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getMiddleName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getTelephone().hashCode();
      hash = (37 * hash) + ASSOCIATION_FIELD_NUMBER;
      hash = (53 * hash) + getAssociation().hashCode();
      if (hasValidUntil()) {
        hash = (37 * hash) + VALIDUNTIL_FIELD_NUMBER;
        hash = (53 * hash) + getValidUntil().hashCode();
      }
      if (hasMemberSince()) {
        hash = (37 * hash) + MEMBERSINCE_FIELD_NUMBER;
        hash = (53 * hash) + getMemberSince().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.passulo.TokenOuterClass.Token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.passulo.TokenOuterClass.Token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passulo.TokenOuterClass.Token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.passulo.v1.Token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.passulo.v1.Token)
        com.passulo.TokenOuterClass.TokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passulo.TokenOuterClass.Token.class, com.passulo.TokenOuterClass.Token.Builder.class);
      }

      // Construct using com.passulo.TokenOuterClass.Token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getValidUntilFieldBuilder();
          getMemberSinceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        firstName_ = "";
        middleName_ = "";
        lastName_ = "";
        gender_ = 0;
        number_ = "";
        status_ = "";
        company_ = "";
        email_ = "";
        telephone_ = "";
        association_ = "";
        validUntil_ = null;
        if (validUntilBuilder_ != null) {
          validUntilBuilder_.dispose();
          validUntilBuilder_ = null;
        }
        memberSince_ = null;
        if (memberSinceBuilder_ != null) {
          memberSinceBuilder_.dispose();
          memberSinceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token getDefaultInstanceForType() {
        return com.passulo.TokenOuterClass.Token.getDefaultInstance();
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token build() {
        com.passulo.TokenOuterClass.Token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token buildPartial() {
        com.passulo.TokenOuterClass.Token result = new com.passulo.TokenOuterClass.Token(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.passulo.TokenOuterClass.Token result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.firstName_ = firstName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.middleName_ = middleName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastName_ = lastName_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.gender_ = gender_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.number_ = number_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.company_ = company_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.telephone_ = telephone_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.association_ = association_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.validUntil_ = validUntilBuilder_ == null
              ? validUntil_
              : validUntilBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.memberSince_ = memberSinceBuilder_ == null
              ? memberSince_
              : memberSinceBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passulo.TokenOuterClass.Token) {
          return mergeFrom((com.passulo.TokenOuterClass.Token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passulo.TokenOuterClass.Token other) {
        if (other == com.passulo.TokenOuterClass.Token.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMiddleName().isEmpty()) {
          middleName_ = other.middleName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (!other.getTelephone().isEmpty()) {
          telephone_ = other.telephone_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (!other.getAssociation().isEmpty()) {
          association_ = other.association_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (other.hasValidUntil()) {
          mergeValidUntil(other.getValidUntil());
        }
        if (other.hasMemberSince()) {
          mergeMemberSince(other.getMemberSince());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                firstName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                middleName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                lastName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                gender_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                company_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                telephone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                association_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                input.readMessage(
                    getValidUntilFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              case 106: {
                input.readMessage(
                    getMemberSinceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00001000;
                break;
              } // case 106
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <pre>
       * identifier for this token only
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * identifier for this token only
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * identifier for this token only
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * identifier for this token only
       * </pre>
       *
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * identifier for this token only
       * </pre>
       *
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        firstName_ = getDefaultInstance().getFirstName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firstName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object middleName_ = "";
      /**
       * <code>string middleName = 3;</code>
       * @return The middleName.
       */
      public java.lang.String getMiddleName() {
        java.lang.Object ref = middleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          middleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string middleName = 3;</code>
       * @return The bytes for middleName.
       */
      public com.google.protobuf.ByteString
          getMiddleNameBytes() {
        java.lang.Object ref = middleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          middleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string middleName = 3;</code>
       * @param value The middleName to set.
       * @return This builder for chaining.
       */
      public Builder setMiddleName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        middleName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string middleName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMiddleName() {
        middleName_ = getDefaultInstance().getMiddleName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string middleName = 3;</code>
       * @param value The bytes for middleName to set.
       * @return This builder for chaining.
       */
      public Builder setMiddleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        middleName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 4;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 4;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 4;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        lastName_ = getDefaultInstance().getLastName();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 4;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastName_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
       * @return The enum numeric value on the wire for gender.
       */
      @java.lang.Override public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
       * @param value The enum numeric value on the wire for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
       * @return The gender.
       */
      @java.lang.Override
      public com.passulo.TokenOuterClass.Token.Gender getGender() {
        com.passulo.TokenOuterClass.Token.Gender result = com.passulo.TokenOuterClass.Token.Gender.forNumber(gender_);
        return result == null ? com.passulo.TokenOuterClass.Token.Gender.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(com.passulo.TokenOuterClass.Token.Gender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.passulo.v1.Token.Gender gender = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 6;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 6;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 6;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string number = 6;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 7;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 7;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 7;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        status_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = getDefaultInstance().getStatus();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string status = 7;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        status_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>string company = 8;</code>
       * @return The company.
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company = 8;</code>
       * @return The bytes for company.
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 8;</code>
       * @param value The company to set.
       * @return This builder for chaining.
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        company_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompany() {
        company_ = getDefaultInstance().getCompany();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string company = 8;</code>
       * @param value The bytes for company to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        company_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 9;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 9;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 9;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 9;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private java.lang.Object telephone_ = "";
      /**
       * <code>string telephone = 10;</code>
       * @return The telephone.
       */
      public java.lang.String getTelephone() {
        java.lang.Object ref = telephone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          telephone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string telephone = 10;</code>
       * @return The bytes for telephone.
       */
      public com.google.protobuf.ByteString
          getTelephoneBytes() {
        java.lang.Object ref = telephone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          telephone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string telephone = 10;</code>
       * @param value The telephone to set.
       * @return This builder for chaining.
       */
      public Builder setTelephone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        telephone_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>string telephone = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTelephone() {
        telephone_ = getDefaultInstance().getTelephone();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>string telephone = 10;</code>
       * @param value The bytes for telephone to set.
       * @return This builder for chaining.
       */
      public Builder setTelephoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        telephone_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private java.lang.Object association_ = "";
      /**
       * <code>string association = 11;</code>
       * @return The association.
       */
      public java.lang.String getAssociation() {
        java.lang.Object ref = association_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          association_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string association = 11;</code>
       * @return The bytes for association.
       */
      public com.google.protobuf.ByteString
          getAssociationBytes() {
        java.lang.Object ref = association_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          association_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string association = 11;</code>
       * @param value The association to set.
       * @return This builder for chaining.
       */
      public Builder setAssociation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        association_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>string association = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssociation() {
        association_ = getDefaultInstance().getAssociation();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>string association = 11;</code>
       * @param value The bytes for association to set.
       * @return This builder for chaining.
       */
      public Builder setAssociationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        association_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp validUntil_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> validUntilBuilder_;
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       * @return Whether the validUntil field is set.
       */
      public boolean hasValidUntil() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       * @return The validUntil.
       */
      public com.google.protobuf.Timestamp getValidUntil() {
        if (validUntilBuilder_ == null) {
          return validUntil_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
        } else {
          return validUntilBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder setValidUntil(com.google.protobuf.Timestamp value) {
        if (validUntilBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          validUntil_ = value;
        } else {
          validUntilBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder setValidUntil(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (validUntilBuilder_ == null) {
          validUntil_ = builderForValue.build();
        } else {
          validUntilBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder mergeValidUntil(com.google.protobuf.Timestamp value) {
        if (validUntilBuilder_ == null) {
          if (((bitField0_ & 0x00000800) != 0) &&
            validUntil_ != null &&
            validUntil_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getValidUntilBuilder().mergeFrom(value);
          } else {
            validUntil_ = value;
          }
        } else {
          validUntilBuilder_.mergeFrom(value);
        }
        if (validUntil_ != null) {
          bitField0_ |= 0x00000800;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder clearValidUntil() {
        bitField0_ = (bitField0_ & ~0x00000800);
        validUntil_ = null;
        if (validUntilBuilder_ != null) {
          validUntilBuilder_.dispose();
          validUntilBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public com.google.protobuf.Timestamp.Builder getValidUntilBuilder() {
        bitField0_ |= 0x00000800;
        onChanged();
        return getValidUntilFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder() {
        if (validUntilBuilder_ != null) {
          return validUntilBuilder_.getMessageOrBuilder();
        } else {
          return validUntil_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getValidUntilFieldBuilder() {
        if (validUntilBuilder_ == null) {
          validUntilBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getValidUntil(),
                  getParentForChildren(),
                  isClean());
          validUntil_ = null;
        }
        return validUntilBuilder_;
      }

      private com.google.protobuf.Timestamp memberSince_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> memberSinceBuilder_;
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       * @return Whether the memberSince field is set.
       */
      public boolean hasMemberSince() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       * @return The memberSince.
       */
      public com.google.protobuf.Timestamp getMemberSince() {
        if (memberSinceBuilder_ == null) {
          return memberSince_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
        } else {
          return memberSinceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder setMemberSince(com.google.protobuf.Timestamp value) {
        if (memberSinceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memberSince_ = value;
        } else {
          memberSinceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder setMemberSince(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (memberSinceBuilder_ == null) {
          memberSince_ = builderForValue.build();
        } else {
          memberSinceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder mergeMemberSince(com.google.protobuf.Timestamp value) {
        if (memberSinceBuilder_ == null) {
          if (((bitField0_ & 0x00001000) != 0) &&
            memberSince_ != null &&
            memberSince_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getMemberSinceBuilder().mergeFrom(value);
          } else {
            memberSince_ = value;
          }
        } else {
          memberSinceBuilder_.mergeFrom(value);
        }
        if (memberSince_ != null) {
          bitField0_ |= 0x00001000;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder clearMemberSince() {
        bitField0_ = (bitField0_ & ~0x00001000);
        memberSince_ = null;
        if (memberSinceBuilder_ != null) {
          memberSinceBuilder_.dispose();
          memberSinceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public com.google.protobuf.Timestamp.Builder getMemberSinceBuilder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getMemberSinceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder() {
        if (memberSinceBuilder_ != null) {
          return memberSinceBuilder_.getMessageOrBuilder();
        } else {
          return memberSince_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getMemberSinceFieldBuilder() {
        if (memberSinceBuilder_ == null) {
          memberSinceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getMemberSince(),
                  getParentForChildren(),
                  isClean());
          memberSince_ = null;
        }
        return memberSinceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.passulo.v1.Token)
    }

    // @@protoc_insertion_point(class_scope:com.passulo.v1.Token)
    private static final com.passulo.TokenOuterClass.Token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passulo.TokenOuterClass.Token();
    }

    public static com.passulo.TokenOuterClass.Token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Token>
        PARSER = new com.google.protobuf.AbstractParser<Token>() {
      @java.lang.Override
      public Token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Token> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passulo.TokenOuterClass.Token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_passulo_v1_Token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_passulo_v1_Token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027com/passulo/token.proto\022\016com.passulo.v" +
      "1\032\037google/protobuf/timestamp.proto\"\377\002\n\005T" +
      "oken\022\n\n\002id\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\022\n\nm" +
      "iddleName\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022,\n\006gen" +
      "der\030\005 \001(\0162\034.com.passulo.v1.Token.Gender\022" +
      "\016\n\006number\030\006 \001(\t\022\016\n\006status\030\007 \001(\t\022\017\n\007compa" +
      "ny\030\010 \001(\t\022\r\n\005email\030\t \001(\t\022\021\n\ttelephone\030\n \001" +
      "(\t\022\023\n\013association\030\013 \001(\t\022.\n\nvalidUntil\030\014 " +
      "\001(\0132\032.google.protobuf.Timestamp\022/\n\013membe" +
      "rSince\030\r \001(\0132\032.google.protobuf.Timestamp" +
      "\":\n\006Gender\022\r\n\tundefined\020\000\022\n\n\006female\020\001\022\010\n" +
      "\004male\020\002\022\013\n\007diverse\020\003B\'\n\013com.passuloZ\030git" +
      "hub.com/passulo/Tokenb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_passulo_v1_Token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_passulo_v1_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_passulo_v1_Token_descriptor,
        new java.lang.String[] { "Id", "FirstName", "MiddleName", "LastName", "Gender", "Number", "Status", "Company", "Email", "Telephone", "Association", "ValidUntil", "MemberSince", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
