// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/passulo/token.proto

package com.passulo;

public final class TokenOuterClass {
  private TokenOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.passulo.v1.Token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string middleName = 3;</code>
     * @return The middleName.
     */
    java.lang.String getMiddleName();
    /**
     * <code>string middleName = 3;</code>
     * @return The bytes for middleName.
     */
    com.google.protobuf.ByteString
        getMiddleNameBytes();

    /**
     * <code>string lastName = 4;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 4;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string gender = 5;</code>
     * @return The gender.
     */
    java.lang.String getGender();
    /**
     * <code>string gender = 5;</code>
     * @return The bytes for gender.
     */
    com.google.protobuf.ByteString
        getGenderBytes();

    /**
     * <code>string number = 6;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 6;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string company = 8;</code>
     * @return The company.
     */
    java.lang.String getCompany();
    /**
     * <code>string company = 8;</code>
     * @return The bytes for company.
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>string email = 9;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 9;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string telephone = 10;</code>
     * @return The telephone.
     */
    java.lang.String getTelephone();
    /**
     * <code>string telephone = 10;</code>
     * @return The bytes for telephone.
     */
    com.google.protobuf.ByteString
        getTelephoneBytes();

    /**
     * <code>string association = 11;</code>
     * @return The association.
     */
    java.lang.String getAssociation();
    /**
     * <code>string association = 11;</code>
     * @return The bytes for association.
     */
    com.google.protobuf.ByteString
        getAssociationBytes();

    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return Whether the validUntil field is set.
     */
    boolean hasValidUntil();
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return The validUntil.
     */
    com.google.protobuf.Timestamp getValidUntil();
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     */
    com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return Whether the memberSince field is set.
     */
    boolean hasMemberSince();
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return The memberSince.
     */
    com.google.protobuf.Timestamp getMemberSince();
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     */
    com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder();
  }
  /**
   * Protobuf type {@code com.passulo.v1.Token}
   */
  public static final class Token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.passulo.v1.Token)
      TokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Token.newBuilder() to construct.
    private Token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Token() {
      id_ = "";
      firstName_ = "";
      middleName_ = "";
      lastName_ = "";
      gender_ = "";
      number_ = "";
      status_ = "";
      company_ = "";
      email_ = "";
      telephone_ = "";
      association_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Token();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              middleName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              gender_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              telephone_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              association_ = s;
              break;
            }
            case 98: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (validUntil_ != null) {
                subBuilder = validUntil_.toBuilder();
              }
              validUntil_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(validUntil_);
                validUntil_ = subBuilder.buildPartial();
              }

              break;
            }
            case 106: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (memberSince_ != null) {
                subBuilder = memberSince_.toBuilder();
              }
              memberSince_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(memberSince_);
                memberSince_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.passulo.TokenOuterClass.Token.class, com.passulo.TokenOuterClass.Token.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIDDLENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object middleName_;
    /**
     * <code>string middleName = 3;</code>
     * @return The middleName.
     */
    @java.lang.Override
    public java.lang.String getMiddleName() {
      java.lang.Object ref = middleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        middleName_ = s;
        return s;
      }
    }
    /**
     * <code>string middleName = 3;</code>
     * @return The bytes for middleName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMiddleNameBytes() {
      java.lang.Object ref = middleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        middleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 4;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 4;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 5;
    private volatile java.lang.Object gender_;
    /**
     * <code>string gender = 5;</code>
     * @return The gender.
     */
    @java.lang.Override
    public java.lang.String getGender() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gender_ = s;
        return s;
      }
    }
    /**
     * <code>string gender = 5;</code>
     * @return The bytes for gender.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenderBytes() {
      java.lang.Object ref = gender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 6;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 6;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 6;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 7;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 7;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 7;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANY_FIELD_NUMBER = 8;
    private volatile java.lang.Object company_;
    /**
     * <code>string company = 8;</code>
     * @return The company.
     */
    @java.lang.Override
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 8;</code>
     * @return The bytes for company.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 9;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 9;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 9;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TELEPHONE_FIELD_NUMBER = 10;
    private volatile java.lang.Object telephone_;
    /**
     * <code>string telephone = 10;</code>
     * @return The telephone.
     */
    @java.lang.Override
    public java.lang.String getTelephone() {
      java.lang.Object ref = telephone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telephone_ = s;
        return s;
      }
    }
    /**
     * <code>string telephone = 10;</code>
     * @return The bytes for telephone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTelephoneBytes() {
      java.lang.Object ref = telephone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telephone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSOCIATION_FIELD_NUMBER = 11;
    private volatile java.lang.Object association_;
    /**
     * <code>string association = 11;</code>
     * @return The association.
     */
    @java.lang.Override
    public java.lang.String getAssociation() {
      java.lang.Object ref = association_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        association_ = s;
        return s;
      }
    }
    /**
     * <code>string association = 11;</code>
     * @return The bytes for association.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssociationBytes() {
      java.lang.Object ref = association_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        association_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALIDUNTIL_FIELD_NUMBER = 12;
    private com.google.protobuf.Timestamp validUntil_;
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return Whether the validUntil field is set.
     */
    @java.lang.Override
    public boolean hasValidUntil() {
      return validUntil_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     * @return The validUntil.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getValidUntil() {
      return validUntil_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
    }
    /**
     * <code>.google.protobuf.Timestamp validUntil = 12;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder() {
      return getValidUntil();
    }

    public static final int MEMBERSINCE_FIELD_NUMBER = 13;
    private com.google.protobuf.Timestamp memberSince_;
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return Whether the memberSince field is set.
     */
    @java.lang.Override
    public boolean hasMemberSince() {
      return memberSince_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     * @return The memberSince.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getMemberSince() {
      return memberSince_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
    }
    /**
     * <code>.google.protobuf.Timestamp memberSince = 13;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder() {
      return getMemberSince();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, middleName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, company_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telephone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, telephone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(association_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, association_);
      }
      if (validUntil_ != null) {
        output.writeMessage(12, getValidUntil());
      }
      if (memberSince_ != null) {
        output.writeMessage(13, getMemberSince());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(middleName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, middleName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(gender_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gender_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, company_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, email_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telephone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, telephone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(association_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, association_);
      }
      if (validUntil_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getValidUntil());
      }
      if (memberSince_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getMemberSince());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.passulo.TokenOuterClass.Token)) {
        return super.equals(obj);
      }
      com.passulo.TokenOuterClass.Token other = (com.passulo.TokenOuterClass.Token) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getMiddleName()
          .equals(other.getMiddleName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getGender()
          .equals(other.getGender())) return false;
      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getCompany()
          .equals(other.getCompany())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getTelephone()
          .equals(other.getTelephone())) return false;
      if (!getAssociation()
          .equals(other.getAssociation())) return false;
      if (hasValidUntil() != other.hasValidUntil()) return false;
      if (hasValidUntil()) {
        if (!getValidUntil()
            .equals(other.getValidUntil())) return false;
      }
      if (hasMemberSince() != other.hasMemberSince()) return false;
      if (hasMemberSince()) {
        if (!getMemberSince()
            .equals(other.getMemberSince())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + MIDDLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getMiddleName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + TELEPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getTelephone().hashCode();
      hash = (37 * hash) + ASSOCIATION_FIELD_NUMBER;
      hash = (53 * hash) + getAssociation().hashCode();
      if (hasValidUntil()) {
        hash = (37 * hash) + VALIDUNTIL_FIELD_NUMBER;
        hash = (53 * hash) + getValidUntil().hashCode();
      }
      if (hasMemberSince()) {
        hash = (37 * hash) + MEMBERSINCE_FIELD_NUMBER;
        hash = (53 * hash) + getMemberSince().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.passulo.TokenOuterClass.Token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.passulo.TokenOuterClass.Token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.passulo.TokenOuterClass.Token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.passulo.v1.Token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.passulo.v1.Token)
        com.passulo.TokenOuterClass.TokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.passulo.TokenOuterClass.Token.class, com.passulo.TokenOuterClass.Token.Builder.class);
      }

      // Construct using com.passulo.TokenOuterClass.Token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        firstName_ = "";

        middleName_ = "";

        lastName_ = "";

        gender_ = "";

        number_ = "";

        status_ = "";

        company_ = "";

        email_ = "";

        telephone_ = "";

        association_ = "";

        if (validUntilBuilder_ == null) {
          validUntil_ = null;
        } else {
          validUntil_ = null;
          validUntilBuilder_ = null;
        }
        if (memberSinceBuilder_ == null) {
          memberSince_ = null;
        } else {
          memberSince_ = null;
          memberSinceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.passulo.TokenOuterClass.internal_static_com_passulo_v1_Token_descriptor;
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token getDefaultInstanceForType() {
        return com.passulo.TokenOuterClass.Token.getDefaultInstance();
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token build() {
        com.passulo.TokenOuterClass.Token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.passulo.TokenOuterClass.Token buildPartial() {
        com.passulo.TokenOuterClass.Token result = new com.passulo.TokenOuterClass.Token(this);
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.middleName_ = middleName_;
        result.lastName_ = lastName_;
        result.gender_ = gender_;
        result.number_ = number_;
        result.status_ = status_;
        result.company_ = company_;
        result.email_ = email_;
        result.telephone_ = telephone_;
        result.association_ = association_;
        if (validUntilBuilder_ == null) {
          result.validUntil_ = validUntil_;
        } else {
          result.validUntil_ = validUntilBuilder_.build();
        }
        if (memberSinceBuilder_ == null) {
          result.memberSince_ = memberSince_;
        } else {
          result.memberSince_ = memberSinceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.passulo.TokenOuterClass.Token) {
          return mergeFrom((com.passulo.TokenOuterClass.Token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.passulo.TokenOuterClass.Token other) {
        if (other == com.passulo.TokenOuterClass.Token.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getMiddleName().isEmpty()) {
          middleName_ = other.middleName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (!other.getGender().isEmpty()) {
          gender_ = other.gender_;
          onChanged();
        }
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getTelephone().isEmpty()) {
          telephone_ = other.telephone_;
          onChanged();
        }
        if (!other.getAssociation().isEmpty()) {
          association_ = other.association_;
          onChanged();
        }
        if (other.hasValidUntil()) {
          mergeValidUntil(other.getValidUntil());
        }
        if (other.hasMemberSince()) {
          mergeMemberSince(other.getMemberSince());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.passulo.TokenOuterClass.Token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.passulo.TokenOuterClass.Token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object middleName_ = "";
      /**
       * <code>string middleName = 3;</code>
       * @return The middleName.
       */
      public java.lang.String getMiddleName() {
        java.lang.Object ref = middleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          middleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string middleName = 3;</code>
       * @return The bytes for middleName.
       */
      public com.google.protobuf.ByteString
          getMiddleNameBytes() {
        java.lang.Object ref = middleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          middleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string middleName = 3;</code>
       * @param value The middleName to set.
       * @return This builder for chaining.
       */
      public Builder setMiddleName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        middleName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string middleName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMiddleName() {
        
        middleName_ = getDefaultInstance().getMiddleName();
        onChanged();
        return this;
      }
      /**
       * <code>string middleName = 3;</code>
       * @param value The bytes for middleName to set.
       * @return This builder for chaining.
       */
      public Builder setMiddleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        middleName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 4;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 4;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 4;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 4;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gender_ = "";
      /**
       * <code>string gender = 5;</code>
       * @return The gender.
       */
      public java.lang.String getGender() {
        java.lang.Object ref = gender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gender = 5;</code>
       * @return The bytes for gender.
       */
      public com.google.protobuf.ByteString
          getGenderBytes() {
        java.lang.Object ref = gender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gender = 5;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = getDefaultInstance().getGender();
        onChanged();
        return this;
      }
      /**
       * <code>string gender = 5;</code>
       * @param value The bytes for gender to set.
       * @return This builder for chaining.
       */
      public Builder setGenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 6;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 6;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 6;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 6;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 7;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 7;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 7;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 7;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <code>string company = 8;</code>
       * @return The company.
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string company = 8;</code>
       * @return The bytes for company.
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 8;</code>
       * @param value The company to set.
       * @return This builder for chaining.
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string company = 8;</code>
       * @param value The bytes for company to set.
       * @return This builder for chaining.
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 9;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 9;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 9;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 9;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object telephone_ = "";
      /**
       * <code>string telephone = 10;</code>
       * @return The telephone.
       */
      public java.lang.String getTelephone() {
        java.lang.Object ref = telephone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          telephone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string telephone = 10;</code>
       * @return The bytes for telephone.
       */
      public com.google.protobuf.ByteString
          getTelephoneBytes() {
        java.lang.Object ref = telephone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          telephone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string telephone = 10;</code>
       * @param value The telephone to set.
       * @return This builder for chaining.
       */
      public Builder setTelephone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        telephone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string telephone = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTelephone() {
        
        telephone_ = getDefaultInstance().getTelephone();
        onChanged();
        return this;
      }
      /**
       * <code>string telephone = 10;</code>
       * @param value The bytes for telephone to set.
       * @return This builder for chaining.
       */
      public Builder setTelephoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        telephone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object association_ = "";
      /**
       * <code>string association = 11;</code>
       * @return The association.
       */
      public java.lang.String getAssociation() {
        java.lang.Object ref = association_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          association_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string association = 11;</code>
       * @return The bytes for association.
       */
      public com.google.protobuf.ByteString
          getAssociationBytes() {
        java.lang.Object ref = association_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          association_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string association = 11;</code>
       * @param value The association to set.
       * @return This builder for chaining.
       */
      public Builder setAssociation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        association_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string association = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssociation() {
        
        association_ = getDefaultInstance().getAssociation();
        onChanged();
        return this;
      }
      /**
       * <code>string association = 11;</code>
       * @param value The bytes for association to set.
       * @return This builder for chaining.
       */
      public Builder setAssociationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        association_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp validUntil_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> validUntilBuilder_;
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       * @return Whether the validUntil field is set.
       */
      public boolean hasValidUntil() {
        return validUntilBuilder_ != null || validUntil_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       * @return The validUntil.
       */
      public com.google.protobuf.Timestamp getValidUntil() {
        if (validUntilBuilder_ == null) {
          return validUntil_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
        } else {
          return validUntilBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder setValidUntil(com.google.protobuf.Timestamp value) {
        if (validUntilBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          validUntil_ = value;
          onChanged();
        } else {
          validUntilBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder setValidUntil(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (validUntilBuilder_ == null) {
          validUntil_ = builderForValue.build();
          onChanged();
        } else {
          validUntilBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder mergeValidUntil(com.google.protobuf.Timestamp value) {
        if (validUntilBuilder_ == null) {
          if (validUntil_ != null) {
            validUntil_ =
              com.google.protobuf.Timestamp.newBuilder(validUntil_).mergeFrom(value).buildPartial();
          } else {
            validUntil_ = value;
          }
          onChanged();
        } else {
          validUntilBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public Builder clearValidUntil() {
        if (validUntilBuilder_ == null) {
          validUntil_ = null;
          onChanged();
        } else {
          validUntil_ = null;
          validUntilBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public com.google.protobuf.Timestamp.Builder getValidUntilBuilder() {
        
        onChanged();
        return getValidUntilFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getValidUntilOrBuilder() {
        if (validUntilBuilder_ != null) {
          return validUntilBuilder_.getMessageOrBuilder();
        } else {
          return validUntil_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : validUntil_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp validUntil = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getValidUntilFieldBuilder() {
        if (validUntilBuilder_ == null) {
          validUntilBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getValidUntil(),
                  getParentForChildren(),
                  isClean());
          validUntil_ = null;
        }
        return validUntilBuilder_;
      }

      private com.google.protobuf.Timestamp memberSince_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> memberSinceBuilder_;
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       * @return Whether the memberSince field is set.
       */
      public boolean hasMemberSince() {
        return memberSinceBuilder_ != null || memberSince_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       * @return The memberSince.
       */
      public com.google.protobuf.Timestamp getMemberSince() {
        if (memberSinceBuilder_ == null) {
          return memberSince_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
        } else {
          return memberSinceBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder setMemberSince(com.google.protobuf.Timestamp value) {
        if (memberSinceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memberSince_ = value;
          onChanged();
        } else {
          memberSinceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder setMemberSince(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (memberSinceBuilder_ == null) {
          memberSince_ = builderForValue.build();
          onChanged();
        } else {
          memberSinceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder mergeMemberSince(com.google.protobuf.Timestamp value) {
        if (memberSinceBuilder_ == null) {
          if (memberSince_ != null) {
            memberSince_ =
              com.google.protobuf.Timestamp.newBuilder(memberSince_).mergeFrom(value).buildPartial();
          } else {
            memberSince_ = value;
          }
          onChanged();
        } else {
          memberSinceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public Builder clearMemberSince() {
        if (memberSinceBuilder_ == null) {
          memberSince_ = null;
          onChanged();
        } else {
          memberSince_ = null;
          memberSinceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public com.google.protobuf.Timestamp.Builder getMemberSinceBuilder() {
        
        onChanged();
        return getMemberSinceFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getMemberSinceOrBuilder() {
        if (memberSinceBuilder_ != null) {
          return memberSinceBuilder_.getMessageOrBuilder();
        } else {
          return memberSince_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : memberSince_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp memberSince = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getMemberSinceFieldBuilder() {
        if (memberSinceBuilder_ == null) {
          memberSinceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getMemberSince(),
                  getParentForChildren(),
                  isClean());
          memberSince_ = null;
        }
        return memberSinceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.passulo.v1.Token)
    }

    // @@protoc_insertion_point(class_scope:com.passulo.v1.Token)
    private static final com.passulo.TokenOuterClass.Token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.passulo.TokenOuterClass.Token();
    }

    public static com.passulo.TokenOuterClass.Token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Token>
        PARSER = new com.google.protobuf.AbstractParser<Token>() {
      @java.lang.Override
      public Token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Token> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.passulo.TokenOuterClass.Token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_passulo_v1_Token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_passulo_v1_Token_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027com/passulo/token.proto\022\016com.passulo.v" +
      "1\032\037google/protobuf/timestamp.proto\"\245\002\n\005T" +
      "oken\022\n\n\002id\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\022\n\nm" +
      "iddleName\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022\016\n\006gen" +
      "der\030\005 \001(\t\022\016\n\006number\030\006 \001(\t\022\016\n\006status\030\007 \001(" +
      "\t\022\017\n\007company\030\010 \001(\t\022\r\n\005email\030\t \001(\t\022\021\n\ttel" +
      "ephone\030\n \001(\t\022\023\n\013association\030\013 \001(\t\022.\n\nval" +
      "idUntil\030\014 \001(\0132\032.google.protobuf.Timestam" +
      "p\022/\n\013memberSince\030\r \001(\0132\032.google.protobuf" +
      ".TimestampB\r\n\013com.passulob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_passulo_v1_Token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_passulo_v1_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_passulo_v1_Token_descriptor,
        new java.lang.String[] { "Id", "FirstName", "MiddleName", "LastName", "Gender", "Number", "Status", "Company", "Email", "Telephone", "Association", "ValidUntil", "MemberSince", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
