// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/passulo/token.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Token_Gender

typedef GPB_ENUM(Token_Gender) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Token_Gender_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Token_Gender_Undefined = 0,
  Token_Gender_Female = 1,
  Token_Gender_Male = 2,
  Token_Gender_Diverse = 3,
};

GPBEnumDescriptor *Token_Gender_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Token_Gender_IsValidValue(int32_t value);

#pragma mark - TokenRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TokenRoot : GPBRootObject
@end

#pragma mark - Token

typedef GPB_ENUM(Token_FieldNumber) {
  Token_FieldNumber_Id_p = 1,
  Token_FieldNumber_FirstName = 2,
  Token_FieldNumber_MiddleName = 3,
  Token_FieldNumber_LastName = 4,
  Token_FieldNumber_Gender = 5,
  Token_FieldNumber_Number = 6,
  Token_FieldNumber_Status = 7,
  Token_FieldNumber_Company = 8,
  Token_FieldNumber_Email = 9,
  Token_FieldNumber_Telephone = 10,
  Token_FieldNumber_Association = 11,
  Token_FieldNumber_ValidUntil = 12,
  Token_FieldNumber_MemberSince = 13,
};

GPB_FINAL @interface Token : GPBMessage

/** identifier for this token only */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *middleName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@property(nonatomic, readwrite) Token_Gender gender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *number;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *company;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *telephone;

@property(nonatomic, readwrite, copy, null_resettable) NSString *association;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *validUntil;
/** Test to see if @c validUntil has been set. */
@property(nonatomic, readwrite) BOOL hasValidUntil;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *memberSince;
/** Test to see if @c memberSince has been set. */
@property(nonatomic, readwrite) BOOL hasMemberSince;

@end

/**
 * Fetches the raw value of a @c Token's @c gender property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Token_Gender_RawValue(Token *message);
/**
 * Sets the raw value of an @c Token's @c gender property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetToken_Gender_RawValue(Token *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
