<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/passulo/token.proto

namespace Com\Passulo\V1;

if (false) {
    /**
     * This class is deprecated. Use Com\Passulo\V1\Token\Gender instead.
     * @deprecated
     */
    class Token_Gender {}
}
class_exists(Token\Gender::class);
@trigger_error('Com\Passulo\V1\Token_Gender is deprecated and will be removed in the next major release. Use Com\Passulo\V1\Token\Gender instead', E_USER_DEPRECATED);

