// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: com/passulo/token.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.passulo;

@kotlin.jvm.JvmName("-initializetoken")
public inline fun token(block: com.passulo.TokenKt.Dsl.() -> kotlin.Unit): com.passulo.TokenOuterClass.Token =
  com.passulo.TokenKt.Dsl._create(com.passulo.TokenOuterClass.Token.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.passulo.v1.Token`
 */
public object TokenKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.passulo.TokenOuterClass.Token.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.passulo.TokenOuterClass.Token.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.passulo.TokenOuterClass.Token = _builder.build()

    /**
     * ```
     * identifier for this token only
     * ```
     *
     * `string id = 1;`
     */
    public var id: kotlin.String
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * identifier for this token only
     * ```
     *
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string firstName = 2;`
     */
    public var firstName: kotlin.String
      @JvmName("getFirstName")
      get() = _builder.getFirstName()
      @JvmName("setFirstName")
      set(value) {
        _builder.setFirstName(value)
      }
    /**
     * `string firstName = 2;`
     */
    public fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * `string middleName = 3;`
     */
    public var middleName: kotlin.String
      @JvmName("getMiddleName")
      get() = _builder.getMiddleName()
      @JvmName("setMiddleName")
      set(value) {
        _builder.setMiddleName(value)
      }
    /**
     * `string middleName = 3;`
     */
    public fun clearMiddleName() {
      _builder.clearMiddleName()
    }

    /**
     * `string lastName = 4;`
     */
    public var lastName: kotlin.String
      @JvmName("getLastName")
      get() = _builder.getLastName()
      @JvmName("setLastName")
      set(value) {
        _builder.setLastName(value)
      }
    /**
     * `string lastName = 4;`
     */
    public fun clearLastName() {
      _builder.clearLastName()
    }

    /**
     * `.com.passulo.v1.Token.Gender gender = 5;`
     */
    public var gender: com.passulo.TokenOuterClass.Token.Gender
      @JvmName("getGender")
      get() = _builder.getGender()
      @JvmName("setGender")
      set(value) {
        _builder.setGender(value)
      }
    public var genderValue: kotlin.Int
      @JvmName("getGenderValue")
      get() = _builder.getGenderValue()
      @JvmName("setGenderValue")
      set(value) {
        _builder.setGenderValue(value)
      }
    /**
     * `.com.passulo.v1.Token.Gender gender = 5;`
     */
    public fun clearGender() {
      _builder.clearGender()
    }

    /**
     * `string number = 6;`
     */
    public var number: kotlin.String
      @JvmName("getNumber")
      get() = _builder.getNumber()
      @JvmName("setNumber")
      set(value) {
        _builder.setNumber(value)
      }
    /**
     * `string number = 6;`
     */
    public fun clearNumber() {
      _builder.clearNumber()
    }

    /**
     * `string status = 7;`
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * `string status = 7;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string company = 8;`
     */
    public var company: kotlin.String
      @JvmName("getCompany")
      get() = _builder.getCompany()
      @JvmName("setCompany")
      set(value) {
        _builder.setCompany(value)
      }
    /**
     * `string company = 8;`
     */
    public fun clearCompany() {
      _builder.clearCompany()
    }

    /**
     * `string email = 9;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 9;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * `string telephone = 10;`
     */
    public var telephone: kotlin.String
      @JvmName("getTelephone")
      get() = _builder.getTelephone()
      @JvmName("setTelephone")
      set(value) {
        _builder.setTelephone(value)
      }
    /**
     * `string telephone = 10;`
     */
    public fun clearTelephone() {
      _builder.clearTelephone()
    }

    /**
     * `string association = 11;`
     */
    public var association: kotlin.String
      @JvmName("getAssociation")
      get() = _builder.getAssociation()
      @JvmName("setAssociation")
      set(value) {
        _builder.setAssociation(value)
      }
    /**
     * `string association = 11;`
     */
    public fun clearAssociation() {
      _builder.clearAssociation()
    }

    /**
     * `.google.protobuf.Timestamp validUntil = 12;`
     */
    public var validUntil: com.google.protobuf.Timestamp
      @JvmName("getValidUntil")
      get() = _builder.getValidUntil()
      @JvmName("setValidUntil")
      set(value) {
        _builder.setValidUntil(value)
      }
    /**
     * `.google.protobuf.Timestamp validUntil = 12;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }
    /**
     * `.google.protobuf.Timestamp validUntil = 12;`
     * @return Whether the validUntil field is set.
     */
    public fun hasValidUntil(): kotlin.Boolean {
      return _builder.hasValidUntil()
    }

    /**
     * `.google.protobuf.Timestamp memberSince = 13;`
     */
    public var memberSince: com.google.protobuf.Timestamp
      @JvmName("getMemberSince")
      get() = _builder.getMemberSince()
      @JvmName("setMemberSince")
      set(value) {
        _builder.setMemberSince(value)
      }
    /**
     * `.google.protobuf.Timestamp memberSince = 13;`
     */
    public fun clearMemberSince() {
      _builder.clearMemberSince()
    }
    /**
     * `.google.protobuf.Timestamp memberSince = 13;`
     * @return Whether the memberSince field is set.
     */
    public fun hasMemberSince(): kotlin.Boolean {
      return _builder.hasMemberSince()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.passulo.TokenOuterClass.Token.copy(block: com.passulo.TokenKt.Dsl.() -> kotlin.Unit): com.passulo.TokenOuterClass.Token =
  com.passulo.TokenKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.passulo.TokenOuterClass.TokenOrBuilder.validUntilOrNull: com.google.protobuf.Timestamp?
  get() = if (hasValidUntil()) getValidUntil() else null

public val com.passulo.TokenOuterClass.TokenOrBuilder.memberSinceOrNull: com.google.protobuf.Timestamp?
  get() = if (hasMemberSince()) getMemberSince() else null

