// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: com/passulo/token.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.passulo;

