<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/passulo/token.proto

namespace GPBMetadata\Com\Passulo;

class Token
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
è
com/passulo/token.protocom.passulo.v1"¥
Token

id (	
	firstName (	

middleName (	
lastName (	
gender (	
number (	
status (	
company (	
email	 (	
	telephone
 (	
association (	.

validUntil (2.google.protobuf.Timestamp/
memberSince (2.google.protobuf.TimestampB
com.passulobproto3'
        , true);

        static::$is_initialized = true;
    }
}

