// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/passulo/token.proto

#include "com/passulo/token.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace com {
namespace passulo {
namespace v1 {
        template <typename>
PROTOBUF_CONSTEXPR Token::Token(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.id_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.firstname_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.middlename_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.lastname_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.number_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.status_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.company_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.email_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.telephone_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.association_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.validuntil_)*/ nullptr,
      /*decltype(_impl_.membersince_)*/ nullptr,
      /*decltype(_impl_.gender_)*/ 0,
    } {}
struct TokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TokenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TokenDefaultTypeInternal() {}
  union {
    Token _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TokenDefaultTypeInternal _Token_default_instance_;
}  // namespace v1
}  // namespace passulo
}  // namespace com
static ::_pb::Metadata file_level_metadata_com_2fpassulo_2ftoken_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_com_2fpassulo_2ftoken_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_com_2fpassulo_2ftoken_2eproto = nullptr;
const ::uint32_t TableStruct_com_2fpassulo_2ftoken_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.firstname_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.middlename_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.lastname_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.gender_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.number_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.company_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.email_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.telephone_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.association_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.validuntil_),
    PROTOBUF_FIELD_OFFSET(::com::passulo::v1::Token, _impl_.membersince_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
    1,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 21, -1, sizeof(::com::passulo::v1::Token)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::com::passulo::v1::_Token_default_instance_._instance,
};
const char descriptor_table_protodef_com_2fpassulo_2ftoken_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\027com/passulo/token.proto\022\016com.passulo.v"
    "1\032\037google/protobuf/timestamp.proto\"\377\002\n\005T"
    "oken\022\n\n\002id\030\001 \001(\t\022\021\n\tfirstName\030\002 \001(\t\022\022\n\nm"
    "iddleName\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022,\n\006gen"
    "der\030\005 \001(\0162\034.com.passulo.v1.Token.Gender\022"
    "\016\n\006number\030\006 \001(\t\022\016\n\006status\030\007 \001(\t\022\017\n\007compa"
    "ny\030\010 \001(\t\022\r\n\005email\030\t \001(\t\022\021\n\ttelephone\030\n \001"
    "(\t\022\023\n\013association\030\013 \001(\t\022.\n\nvalidUntil\030\014 "
    "\001(\0132\032.google.protobuf.Timestamp\022/\n\013membe"
    "rSince\030\r \001(\0132\032.google.protobuf.Timestamp"
    "\":\n\006Gender\022\r\n\tundefined\020\000\022\n\n\006female\020\001\022\010\n"
    "\004male\020\002\022\013\n\007diverse\020\003B\'\n\013com.passuloZ\030git"
    "hub.com/passulo/Tokenb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_com_2fpassulo_2ftoken_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_com_2fpassulo_2ftoken_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_com_2fpassulo_2ftoken_2eproto = {
    false,
    false,
    509,
    descriptor_table_protodef_com_2fpassulo_2ftoken_2eproto,
    "com/passulo/token.proto",
    &descriptor_table_com_2fpassulo_2ftoken_2eproto_once,
    descriptor_table_com_2fpassulo_2ftoken_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_com_2fpassulo_2ftoken_2eproto::offsets,
    file_level_metadata_com_2fpassulo_2ftoken_2eproto,
    file_level_enum_descriptors_com_2fpassulo_2ftoken_2eproto,
    file_level_service_descriptors_com_2fpassulo_2ftoken_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_com_2fpassulo_2ftoken_2eproto_getter() {
  return &descriptor_table_com_2fpassulo_2ftoken_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_com_2fpassulo_2ftoken_2eproto(&descriptor_table_com_2fpassulo_2ftoken_2eproto);
namespace com {
namespace passulo {
namespace v1 {
const ::google::protobuf::EnumDescriptor* Token_Gender_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_com_2fpassulo_2ftoken_2eproto);
  return file_level_enum_descriptors_com_2fpassulo_2ftoken_2eproto[0];
}
bool Token_Gender_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Token_Gender Token::undefined;
constexpr Token_Gender Token::female;
constexpr Token_Gender Token::male;
constexpr Token_Gender Token::diverse;
constexpr Token_Gender Token::Gender_MIN;
constexpr Token_Gender Token::Gender_MAX;
constexpr int Token::Gender_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Token::_Internal {
 public:
  using HasBits = decltype(std::declval<Token>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Token, _impl_._has_bits_);
  static const ::google::protobuf::Timestamp& validuntil(const Token* msg);
  static void set_has_validuntil(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::google::protobuf::Timestamp& membersince(const Token* msg);
  static void set_has_membersince(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::google::protobuf::Timestamp& Token::_Internal::validuntil(const Token* msg) {
  return *msg->_impl_.validuntil_;
}
const ::google::protobuf::Timestamp& Token::_Internal::membersince(const Token* msg) {
  return *msg->_impl_.membersince_;
}
void Token::clear_validuntil() {
  if (_impl_.validuntil_ != nullptr) _impl_.validuntil_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Token::clear_membersince() {
  if (_impl_.membersince_ != nullptr) _impl_.membersince_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
Token::Token(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:com.passulo.v1.Token)
}
Token::Token(const Token& from) : ::google::protobuf::Message() {
  Token* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.id_){},
      decltype(_impl_.firstname_){},
      decltype(_impl_.middlename_){},
      decltype(_impl_.lastname_){},
      decltype(_impl_.number_){},
      decltype(_impl_.status_){},
      decltype(_impl_.company_){},
      decltype(_impl_.email_){},
      decltype(_impl_.telephone_){},
      decltype(_impl_.association_){},
      decltype(_impl_.validuntil_){nullptr},
      decltype(_impl_.membersince_){nullptr},
      decltype(_impl_.gender_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), _this->GetArenaForAllocation());
  }
  _impl_.firstname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.firstname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_firstname().empty()) {
    _this->_impl_.firstname_.Set(from._internal_firstname(), _this->GetArenaForAllocation());
  }
  _impl_.middlename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.middlename_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_middlename().empty()) {
    _this->_impl_.middlename_.Set(from._internal_middlename(), _this->GetArenaForAllocation());
  }
  _impl_.lastname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.lastname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lastname().empty()) {
    _this->_impl_.lastname_.Set(from._internal_lastname(), _this->GetArenaForAllocation());
  }
  _impl_.number_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.number_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_number().empty()) {
    _this->_impl_.number_.Set(from._internal_number(), _this->GetArenaForAllocation());
  }
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.status_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_status().empty()) {
    _this->_impl_.status_.Set(from._internal_status(), _this->GetArenaForAllocation());
  }
  _impl_.company_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.company_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_company().empty()) {
    _this->_impl_.company_.Set(from._internal_company(), _this->GetArenaForAllocation());
  }
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.email_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_email().empty()) {
    _this->_impl_.email_.Set(from._internal_email(), _this->GetArenaForAllocation());
  }
  _impl_.telephone_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.telephone_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_telephone().empty()) {
    _this->_impl_.telephone_.Set(from._internal_telephone(), _this->GetArenaForAllocation());
  }
  _impl_.association_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.association_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_association().empty()) {
    _this->_impl_.association_.Set(from._internal_association(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.validuntil_ = new ::google::protobuf::Timestamp(*from._impl_.validuntil_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.membersince_ = new ::google::protobuf::Timestamp(*from._impl_.membersince_);
  }
  _this->_impl_.gender_ = from._impl_.gender_;

  // @@protoc_insertion_point(copy_constructor:com.passulo.v1.Token)
}
inline void Token::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.id_){},
      decltype(_impl_.firstname_){},
      decltype(_impl_.middlename_){},
      decltype(_impl_.lastname_){},
      decltype(_impl_.number_){},
      decltype(_impl_.status_){},
      decltype(_impl_.company_){},
      decltype(_impl_.email_){},
      decltype(_impl_.telephone_){},
      decltype(_impl_.association_){},
      decltype(_impl_.validuntil_){nullptr},
      decltype(_impl_.membersince_){nullptr},
      decltype(_impl_.gender_){0},
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.firstname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.firstname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.middlename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.middlename_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastname_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.lastname_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.number_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.number_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.status_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.status_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.company_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.company_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.email_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.email_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.telephone_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.telephone_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.association_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.association_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Token::~Token() {
  // @@protoc_insertion_point(destructor:com.passulo.v1.Token)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Token::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
  _impl_.firstname_.Destroy();
  _impl_.middlename_.Destroy();
  _impl_.lastname_.Destroy();
  _impl_.number_.Destroy();
  _impl_.status_.Destroy();
  _impl_.company_.Destroy();
  _impl_.email_.Destroy();
  _impl_.telephone_.Destroy();
  _impl_.association_.Destroy();
  if (this != internal_default_instance()) delete _impl_.validuntil_;
  if (this != internal_default_instance()) delete _impl_.membersince_;
}
void Token::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Token::Clear() {
// @@protoc_insertion_point(message_clear_start:com.passulo.v1.Token)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.firstname_.ClearToEmpty();
  _impl_.middlename_.ClearToEmpty();
  _impl_.lastname_.ClearToEmpty();
  _impl_.number_.ClearToEmpty();
  _impl_.status_.ClearToEmpty();
  _impl_.company_.ClearToEmpty();
  _impl_.email_.ClearToEmpty();
  _impl_.telephone_.ClearToEmpty();
  _impl_.association_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.validuntil_ != nullptr);
      _impl_.validuntil_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.membersince_ != nullptr);
      _impl_.membersince_->Clear();
    }
  }
  _impl_.gender_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Token::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 2, 110, 2> Token::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Token, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Token_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.id_)}},
    // string firstName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.firstname_)}},
    // string middleName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.middlename_)}},
    // string lastName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.lastname_)}},
    // .com.passulo.v1.Token.Gender gender = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Token, _impl_.gender_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.gender_)}},
    // string number = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.number_)}},
    // string status = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.status_)}},
    // string company = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.company_)}},
    // string email = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.email_)}},
    // string telephone = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.telephone_)}},
    // string association = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.association_)}},
    // .google.protobuf.Timestamp validUntil = 12;
    {::_pbi::TcParser::FastMtS1,
     {98, 0, 0, PROTOBUF_FIELD_OFFSET(Token, _impl_.validuntil_)}},
    // .google.protobuf.Timestamp memberSince = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 1, 1, PROTOBUF_FIELD_OFFSET(Token, _impl_.membersince_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string firstName = 2;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.firstname_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string middleName = 3;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.middlename_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string lastName = 4;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.lastname_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .com.passulo.v1.Token.Gender gender = 5;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.gender_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string number = 6;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.number_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string status = 7;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.status_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string company = 8;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.company_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string email = 9;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.email_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string telephone = 10;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.telephone_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string association = 11;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.association_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Timestamp validUntil = 12;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.validuntil_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp memberSince = 13;
    {PROTOBUF_FIELD_OFFSET(Token, _impl_.membersince_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
    "\24\2\11\12\10\0\6\6\7\5\11\13\0\0\0\0"
    "com.passulo.v1.Token"
    "id"
    "firstName"
    "middleName"
    "lastName"
    "number"
    "status"
    "company"
    "email"
    "telephone"
    "association"
  }},
};

::uint8_t* Token::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.passulo.v1.Token)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    const std::string& _s = this->_internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string firstName = 2;
  if (!this->_internal_firstname().empty()) {
    const std::string& _s = this->_internal_firstname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.firstName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string middleName = 3;
  if (!this->_internal_middlename().empty()) {
    const std::string& _s = this->_internal_middlename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.middleName");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string lastName = 4;
  if (!this->_internal_lastname().empty()) {
    const std::string& _s = this->_internal_lastname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.lastName");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // .com.passulo.v1.Token.Gender gender = 5;
  if (this->_internal_gender() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        5, this->_internal_gender(), target);
  }

  // string number = 6;
  if (!this->_internal_number().empty()) {
    const std::string& _s = this->_internal_number();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.number");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // string status = 7;
  if (!this->_internal_status().empty()) {
    const std::string& _s = this->_internal_status();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.status");
    target = stream->WriteStringMaybeAliased(7, _s, target);
  }

  // string company = 8;
  if (!this->_internal_company().empty()) {
    const std::string& _s = this->_internal_company();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.company");
    target = stream->WriteStringMaybeAliased(8, _s, target);
  }

  // string email = 9;
  if (!this->_internal_email().empty()) {
    const std::string& _s = this->_internal_email();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.email");
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // string telephone = 10;
  if (!this->_internal_telephone().empty()) {
    const std::string& _s = this->_internal_telephone();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.telephone");
    target = stream->WriteStringMaybeAliased(10, _s, target);
  }

  // string association = 11;
  if (!this->_internal_association().empty()) {
    const std::string& _s = this->_internal_association();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "com.passulo.v1.Token.association");
    target = stream->WriteStringMaybeAliased(11, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Timestamp validUntil = 12;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::validuntil(this),
        _Internal::validuntil(this).GetCachedSize(), target, stream);
  }

  // .google.protobuf.Timestamp memberSince = 13;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(13, _Internal::membersince(this),
        _Internal::membersince(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.passulo.v1.Token)
  return target;
}

::size_t Token::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.passulo.v1.Token)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_id());
  }

  // string firstName = 2;
  if (!this->_internal_firstname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_firstname());
  }

  // string middleName = 3;
  if (!this->_internal_middlename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_middlename());
  }

  // string lastName = 4;
  if (!this->_internal_lastname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_lastname());
  }

  // string number = 6;
  if (!this->_internal_number().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_number());
  }

  // string status = 7;
  if (!this->_internal_status().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_status());
  }

  // string company = 8;
  if (!this->_internal_company().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_company());
  }

  // string email = 9;
  if (!this->_internal_email().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_email());
  }

  // string telephone = 10;
  if (!this->_internal_telephone().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_telephone());
  }

  // string association = 11;
  if (!this->_internal_association().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_association());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // .google.protobuf.Timestamp validUntil = 12;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.validuntil_);
    }

    // .google.protobuf.Timestamp memberSince = 13;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *_impl_.membersince_);
    }

  }
  // .com.passulo.v1.Token.Gender gender = 5;
  if (this->_internal_gender() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_gender());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Token::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Token::MergeImpl
};
const ::google::protobuf::Message::ClassData*Token::GetClassData() const { return &_class_data_; }


void Token::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Token*>(&to_msg);
  auto& from = static_cast<const Token&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.passulo.v1.Token)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_firstname().empty()) {
    _this->_internal_set_firstname(from._internal_firstname());
  }
  if (!from._internal_middlename().empty()) {
    _this->_internal_set_middlename(from._internal_middlename());
  }
  if (!from._internal_lastname().empty()) {
    _this->_internal_set_lastname(from._internal_lastname());
  }
  if (!from._internal_number().empty()) {
    _this->_internal_set_number(from._internal_number());
  }
  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (!from._internal_company().empty()) {
    _this->_internal_set_company(from._internal_company());
  }
  if (!from._internal_email().empty()) {
    _this->_internal_set_email(from._internal_email());
  }
  if (!from._internal_telephone().empty()) {
    _this->_internal_set_telephone(from._internal_telephone());
  }
  if (!from._internal_association().empty()) {
    _this->_internal_set_association(from._internal_association());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_validuntil()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_validuntil());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_membersince()->::google::protobuf::Timestamp::MergeFrom(
          from._internal_membersince());
    }
  }
  if (from._internal_gender() != 0) {
    _this->_internal_set_gender(from._internal_gender());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Token::CopyFrom(const Token& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.passulo.v1.Token)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Token::IsInitialized() const {
  return true;
}

void Token::InternalSwap(Token* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, lhs_arena,
                                       &other->_impl_.id_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.firstname_, lhs_arena,
                                       &other->_impl_.firstname_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.middlename_, lhs_arena,
                                       &other->_impl_.middlename_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.lastname_, lhs_arena,
                                       &other->_impl_.lastname_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.number_, lhs_arena,
                                       &other->_impl_.number_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, lhs_arena,
                                       &other->_impl_.status_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.company_, lhs_arena,
                                       &other->_impl_.company_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, lhs_arena,
                                       &other->_impl_.email_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.telephone_, lhs_arena,
                                       &other->_impl_.telephone_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.association_, lhs_arena,
                                       &other->_impl_.association_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Token, _impl_.gender_)
      + sizeof(Token::_impl_.gender_)
      - PROTOBUF_FIELD_OFFSET(Token, _impl_.validuntil_)>(
          reinterpret_cast<char*>(&_impl_.validuntil_),
          reinterpret_cast<char*>(&other->_impl_.validuntil_));
}

::google::protobuf::Metadata Token::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_com_2fpassulo_2ftoken_2eproto_getter, &descriptor_table_com_2fpassulo_2ftoken_2eproto_once,
      file_level_metadata_com_2fpassulo_2ftoken_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace passulo
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
