# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/passulo/token.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("com/passulo/token.proto", :syntax => :proto3) do
    add_message "com.passulo.v1.Token" do
      optional :id, :string, 1
      optional :firstName, :string, 2
      optional :middleName, :string, 3
      optional :lastName, :string, 4
      optional :gender, :enum, 5, "com.passulo.v1.Token.Gender"
      optional :number, :string, 6
      optional :status, :string, 7
      optional :company, :string, 8
      optional :email, :string, 9
      optional :telephone, :string, 10
      optional :association, :string, 11
      optional :validUntil, :message, 12, "google.protobuf.Timestamp"
      optional :memberSince, :message, 13, "google.protobuf.Timestamp"
    end
    add_enum "com.passulo.v1.Token.Gender" do
      value :undefined, 0
      value :female, 1
      value :male, 2
      value :diverse, 3
    end
  end
end

module Com
  module Passulo
    module V1
      Token = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.passulo.v1.Token").msgclass
      Token::Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.passulo.v1.Token.Gender").enummodule
    end
  end
end
